### ISSUE TITLE
CPU Timestamp format and precision 

### ISSUE THREAD

**Issue by sflis** [cta-chec/SSDAQ#38]
## Problem:
Currently the implemented timestamping (cpu time) in PR #36 (which also concerns the change in naming scheme and data format #30 ,#31)  is using the python native `datetime` module which returns a utc timestamp as a float meaning it only has microsecond precision and it will loose precision over time. In general this is not a problem as the slow signal data does not need nanosecond and maybe even microsecond precision. However, the data will be compared and matched to other data which uses high precision timestamps representing the time as a tuple of uin64 (seconds,nano seconds), 

## Proposed solution:
For now I propose to convert the `datetime` timestamp to seconds and nano seconds and put it in two fields even though the nano seconds field in reality only has microsecond precision. This format will be directly compatible with timestamps from other data and will be future proof when python gets native ns precision support  in v3.7 ( https://www.python.org/dev/peps/pep-0564/#rationale). For convenience I'll also keep the native `datetime` float timestamp. Which means that the data fields on the SS data would  be:  

```
iro      #readout numner/index
time     #TACK timestamp 
cpu_t    #native python timestamp float64
cpu_t_s  #seconds time stamp uint64 
cpu_t_ns #nano seconds time stamp uint64 
data     #2D data array containing slow signal voltage readout
```

**Comment by sflis** [comment]
commit 04cf999a6 has the fixes I propose

**Comment by watsonjj** [comment]
This is fine. But just as an alternative suggestion, one can use the pandas method:
```python
datetime = pd.to_datetime(
            np.int64(self.current_cpu_s * 1E9) + np.int64(self.current_cpu_ns),
            unit='ns'
        )
```
Which is what I do for the cpu timestamp in the DL1 files to keep the ns precision.

**Comment by sflis** [comment]
> This is fine. But just as an alternative suggestion, one can use the pandas method:
> 
> ```python
> datetime = pd.to_datetime(
>             np.int64(self.current_cpu_s * 1E9) + np.int64(self.current_cpu_ns),
>             unit='ns'
>         )
> ```
> 
> Which is what I do for the cpu timestamp in the DL1 files to keep the ns precision.

Yeah, from what I understand it uses numpy's datetime format which is restricted to 64 bits. One can express delta times with precision down to attoseconds but the time range of course gets shorter with higher precision. 

With python 3.7 and  `time.time_ns()` which gives a decimal type timestamp in nanoseconds we would need two 64 bit integers to store the time correctly anyway, which makes the current solution future compatible.
